name: Code quality
on: push
jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Check formatting with Black
        run: |
          black --check --verbose .
      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff check --select=E9,F63,F7,F82 --target-version=py311 .
          # default set of ruff rules
          ruff check --target-version=py311 .
      - name: Test with pytest
        run: |
          pytest
